apiVersion: v1
kind: Secret
metadata:
  name: rhosak-secret
  labels:
    {{- include "debezium-connect.labels" . | nindent 4 }}
type: Opaque
data:
  client-secret: {{ .Values.connect.authentication.password | b64enc }}