connect:
  name: debezium-rhosak-connect-cluster
  version: '3.2.3'

  bootstrapServers: 
    - rh-summit-cdcjli-j-icd-sb-es-a.bf2.kafka.rhcloud.com:443

  configPrefix: cdc

  authentication:
    username: 00067379-19b3-4b86-a79e-a49a62fe871a
    password: n0ryobDMSB8O8OgOdKvebqCd50s2NjQs

connector:
  enabled: True
  tasksMax: 1
  database: cdc
  config:
    database.dbname: cdc-order
    database.hostname: postgresql
    database.password: dbpassword
    database.port: 5432
    database.user: postgres
    plugin.name: pgoutput