connect:
  bootstrapServers:
    - rh-summit-cdd-p-e--ijauqg--f-g.bf2.kafka.rhcloud.com:443

  authentication:
    username: d9a53966-af70-41e4-a4e8-47aa9f0c62d1
    password: VuUrKzNaTKqkuKVUGKIBjj8GmVGoPGMx