connect:
  name: debezium-rhosak-connect-cluster
  version: '3.2.3'

  bootstrapServers: 
    - <<BOOTSTAP_SERVER_URL>>

  configPrefix: cdc

  authentication:
    username: <<CLIENT_ID>>
    password: <<CLIENT_SECRET>>

connector:
  enabled: True
  tasksMax: 1
  database: cdc
  config:
    database.dbname: cdc-order
    database.hostname: postgresql
    database.password: dbpassword
    database.port: 5432
    database.user: postgres
    plugin.name: pgoutput